name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Make gradlew executable
        run: chmod +x ingest/gradlew

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JAR
        working-directory: ingest
        run: ./gradlew bootJar
      
      - name: Check files
        working-directory: ingest
        run: ls -lh build/libs/

      - name: Upload JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: ingest/build/libs/ingest-0.0.1-SNAPSHOT.jar
          target: /home/ubuntu/service/

      - name: Restart Spring Boot App
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "Stopping existing Spring Boot app if running..."
            sudo systemctl stop ingest
            pkill -f 'java -jar' || echo "No running process found"

            echo "Updating JAR..."
            mv -f /home/ubuntu/service/ingest-0.0.1-SNAPSHOT.jar /home/ubuntu/service/ingest.jar

            echo "Restarting systemd service..."
            sudo systemctl daemon-reload
            sudo systemctl restart ingest

            echo "Checking status..."
            sudo systemctl status ingest --no-pager
